apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server
  namespace: akshit-pipeline-app-1
  labels:
    app: node-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-server
  template:
    metadata:
      labels:
        app: node-server
    spec:
      containers:
      - name: node-server
        image: akshitmadanharness/pipeline-project-1-node-server:v2
        ports:
        - containerPort: 3000
        - containerPort: 9090
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
