apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
  namespace: akshit-pipeline-app-1
spec:
  selector:
    app: react-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  type: LoadBalancer
