apiVersion: v1
kind: Service
metadata:
  name: node-server-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: node-server
  ports:
    - protocol: TCP
      port: {{ .Values.nodeServer.service.port }}
      targetPort: {{ .Values.nodeServer.service.port }}
  type: {{ .Values.nodeServer.service.type }}
