apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- react-frontend-rollout.yaml
- react-frontend-service.yaml
- react-frontend-preview-service.yaml
- node-server-rollout.yaml
- node-server-preview-service.yaml
