apiVersion: v1
kind: Service
metadata:
  name: node-server-preview
  namespace: ns-akshit-pipeline-app-1
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: node-server
