apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: react-frontend
  namespace: ns-akshit-pipeline-app-1
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
      - name: react-frontend
        image: akshitmadanharness/pipeline-project-1-react-frontend:v2
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"
  strategy:
    canary:
      canaryService: react-frontend-preview
      stableService: react-frontend
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
